# Generated by Django 6.0.5 on 2026-05-26 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('html_css', 'HTML5 i CSS3 — Podstawy'), ('html_adv', 'HTML5 — Zaawansowany'), ('css_adv', 'CSS3 — Zaawansowany')], max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zapis na kurs',
                'verbose_name_plural': 'Zapisy na kursy',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='minikurs.enrollment')),
            ],
            options={
                'verbose_name': 'Certyfikat',
                'verbose_name_plural': 'Certyfikaty',
            },
        ),
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(choices=[('glowna', '🏠 Strona główna kursu'), ('html', '📖 HTML — Poradnik'), ('css', '🎨 CSS — Poradnik'), ('sprawdzian', '✅ Sprawdzian'), ('lista', '📋 Lista'), ('tabela_kolorow', '🎨 Tabela kolorów'), ('tabele_listy_lacza', '🔗 Tabele, Listy i Łącza'), ('multimedia', '🎬 Multimedia'), ('formularze_resumo', '📄 Formularz CV'), ('formularze_kwestionariusz', '📋 Kwestionariusz'), ('o_mnie', '👤 O mnie'), ('linki', '🔗 Linki'), ('kontakt', '📞 Kontakt')], max_length=40)),
                ('visited_at', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postęp rozdziału',
                'verbose_name_plural': 'Postępy rozdziałów',
                'ordering': ['-visited_at'],
                'unique_together': {('user', 'chapter')},
            },
        ),
    ]
